Update to dotfiles on Sun Mar 31 19:09:12 CEST 2019

diff --git a/.scripts/tools/fontconfig b/.scripts/tools/fontconfig
--- a/.scripts/tools/fontconfig
+++ b/.scripts/tools/fontconfig
@@ -5,7 +5,6 @@ delete_current_config() { # Deletes the current configuration
 	read answer
 	if [ "$answer" != "${answer#[Yy]}" ] ;then
 		sudo rm -rf /etc/fonts/conf.d/*
-		sudo rm -rf /usr/share/fonts/TTF/Hack*.ttf
 	fi
 }
 
@@ -14,29 +13,44 @@ install_font_pkg() { # Installs needed packages
 		noto-fonts-cjk ttf-symbola ttf-roboto ttf-dejavu \
 		>/dev/null 2>&1
 
-	install_hack
+	# Hack
+	echo "Installing Hack Nerd Font..."
+	install_font_from_git "Hack Regular.ttf" \
+		"https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Hack/Regular/complete/Hack%20Regular%20Nerd%20Font%20Complete.ttf"
+	install_font_from_git "Hack Bold.ttf" \
+		"https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Hack/Bold/complete/Hack%20Bold%20Nerd%20Font%20Complete.ttf"
+	install_font_from_git "Hack Italic.ttf" \
+		"https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Hack/Italic/complete/Hack%20Italic%20Nerd%20Font%20Complete.ttf"
+	install_font_from_git "Hack BoldItalic.ttf" \
+		"https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Hack/BoldItalic/complete/Hack%20Bold%20Italic%20Nerd%20Font%20Complete.ttf"
+
+	# Fura Code
+	echo "Installing Fura Code Nerd Font..."
+	install_font_from_git "FuraCode Regular.ttf" \
+		"https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/FiraCode/Regular/complete/Fura%20Code%20Regular%20Nerd%20Font%20Complete.ttf"
+	install_font_from_git "FuraCoda Bold.ttf" \
+		"https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/FiraCode/Bold/complete/Fura%20Code%20Bold%20Nerd%20Font%20Complete.ttf"
+
+	# Sauce Code Pro
+	echo "Installing Sauce Code Pro Nerd Font"
+	install_font_from_git "Sauce Code Pro Regular.ttf" \
+		"https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/SourceCodePro/Regular/complete/Sauce%20Code%20Pro%20Nerd%20Font%20Complete.ttf"
+	install_font_from_git "Sauce Code Pro Bold.ttf" \
+		"https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/SourceCodePro/Bold/complete/Sauce%20Code%20Pro%20Bold%20Nerd%20Font%20Complete.ttf"
+	install_font_from_git "Sauce Code Pro BoldItalic.ttf" \
+		"https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/SourceCodePro/Bold-Italic/complete/Sauce%20Code%20Pro%20Bold%20Italic%20Nerd%20Font%20Complete.ttf"
 }
 
-install_hack() { # We get Hack Nerd Font directly from GitHub cause why not?
-	# https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/Hack/Bold/complete/Hack%20Bold%20Nerd%20Font%20Complete.ttf
-	# https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/Hack/BoldItalic/complete/Hack%20Bold%20Italic%20Nerd%20Font%20Complete.ttf
-	# https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/Hack/Italic/complete/Hack%20Italic%20Nerd%20Font%20Complete.ttf
-	# https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/Hack/Regular/complete/Hack%20Regular%20Nerd%20Font%20Complete.ttf
-
-	hack_fonts=("https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Hack/Bold/complete/Hack%20Bold%20Nerd%20Font%20Complete.ttf" \
-	"https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Hack/BoldItalic/complete/Hack%20Bold%20Italic%20Nerd%20Font%20Complete.ttf" \
-	"https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Hack/Italic/complete/Hack%20Italic%20Nerd%20Font%20Complete.ttf" \
-	"https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Hack/Regular/complete/Hack%20Regular%20Nerd%20Font%20Complete.ttf")
-
-	dir=$(mktemp -d); (:;:)
-	echo "Installing Hack Nerd Font..."
-	for i in "${hack_fonts[@]}"; do
-		# echo "Downloading $i..."
-		cd $dir
-		sudo curl -LO $i >/dev/null 2>&1
-	done
-
-	sudo cp -r $dir/* /usr/share/fonts/TTF && (:;:)
+install_font_from_git() {
+	# Usage: install_font_from_git font_name font_url
+	# We first download in a temporary directory so in
+	# case the download fails, we don't end up littering /usr/share/..
+	dir=$(mktemp -d)
+	(:;:)		# Micro sleep
+	cd $dir || return 1
+	sudo curl -fLo "$1" "$2" >/dev/null 2>&1
+	sudo cp -f $dir/* /usr/share/fonts/TTF
+	(:;:)
 	sudo rm -rf $dir
 }
 
@@ -55,8 +69,7 @@ install_new_config() { # Symlinks configuration files to /etc/fonts/conf.d
 }
 
 main() {
-	echo "Deleting current font configuration..."
-	delete_current_config || echo "Failed to delete \
+	delete_current_config || echo "Didn't delete \
 		current font configuration!"
 
 	echo "Installing font packages..."
