Update to dotfiles on Thu 13 Jun 2019 01:22:22 AM CEST

diff --git a/.scripts/tools/fontconfig b/.scripts/tools/fontconfig
--- a/.scripts/tools/fontconfig
+++ b/.scripts/tools/fontconfig
@@ -24,7 +24,8 @@ installFontPkg() { # Installs needed packages
 
 	# getNerdFont "3270" || echo ">>Failed to install 3270"
 	# getNerdFont "AnonymousPro" || echo ">>Failed to install AnonymousPro"
-	getNerdFont "Hack" || echo ">>Failed to install Hack"
+	# getNerdFont "Hack" || echo ">>Failed to install Hack"
+	getNerdFont "Meslo" || echo ">>Failed to install Hack"
 	# getNerdFont "FiraCode" ||  echo ">> Failed to install FiraCode"
 	# getNerdFont "SourceCodePro" || echo ">> Failed to install SourceCodePro"
 	# getNerdFont "Ubuntu" || echo ">> Failed to install Ubuntu"
@@ -37,6 +38,7 @@ deleteNerdFonts() {
 	sudo rm -rf -- /usr/share/fonts/TTF/*Nerd\ Font*.ttf
 	sudo rm -rf -- /usr/share/fonts/TTF/Sauce\ Code Pro*.ttf
 	sudo rm -rf -- /usr/share/fonts/TTF/FuraCode*.ttf
+	sudo rm -rf -- /usr/share/fonts/TTF/Meslo*.otf
 }
 
 getNerdFont() { # Downloads and installs a nerd font given a name
@@ -54,11 +56,15 @@ getNerdFont() { # Downloads and installs a nerd font given a name
 	echo "> Extracting archive..."
 	unzip -d . "tmp.zip" >/dev/null 2>&1
 	rm -f -- *Compatible.ttf
+	rm -f -- *Compatible.otf
 	rm -f -- *Mono.ttf
+	rm -f -- *Mono.otf
 	rm -f -- *.zip
 	echo "> Installing these font files for $name:"
 	ls -- *.ttf
+	ls -- *.otf
 	sudo mv -f ./*.ttf /usr/share/fonts/TTF/
+	sudo mv -f ./*.otf /usr/share/fonts/OTF/
 	(:;:)
 	echo "> Done! Cleaning up now..."
 	rm -rf "$dir"
